Repository cargo-public-api/cargo-public-api, pull requests merged in 2022-11, with the labels that each got.

#197 public_api: Remove deprecated `fn public_api_from_rustdoc_json_str()`
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/public-api.txt
  public-api/src/lib.rs
Labels: category-public_api

#198 Group items logically when sorting them
  cargo-public-api/src/main.rs
  cargo-public-api/tests/expected-output/diff_published.txt
  cargo-public-api/tests/expected-output/example_api-v0.3.0.txt
  cargo-public-api/tests/expected-output/example_api_diff_v0.1.0_to_v0.2.0.txt
  cargo-public-api/tests/expected-output/example_api_diff_v0.1.0_to_v0.2.0_colored.txt
  cargo-public-api/tests/expected-output/example_api_v0.3.0_colored.txt
  cargo-public-api/tests/expected-output/features-featall.txt
  cargo-public-api/tests/expected-output/features-featnone.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_afeature_bfeature_c.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_b.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_c.txt
  cargo-public-api/tests/expected-output/lint_error_list.txt
  cargo-public-api/tests/expected-output/public_api_list.txt
  cargo-public-api/tests/expected-output/rustdoc_json_list.txt
  cargo-public-api/tests/expected-output/test_repo_api_latest.txt
  public-api/public-api.txt
  public-api/src/diff.rs
  public-api/src/intermediate_public_item.rs
  public-api/src/item_processor.rs
  public-api/src/lib.rs
  public-api/src/public_item.rs
  public-api/src/render.rs
  public-api/tests/expected-output/comprehensive_api.txt
  public-api/tests/expected-output/comprehensive_api_proc_macro.txt
  public-api/tests/expected-output/diff_with_added_items.txt
  public-api/tests/expected-output/diff_with_removed_items.txt
  public-api/tests/expected-output/example_api-v0.2.0-with-blanket-implementations.txt
  public-api/tests/expected-output/print_diff.txt
  public-api/tests/expected-output/print_diff_reversed.txt
  rustdoc-json/public-api.txt
  test-apis/comprehensive_api/src/impls.rs
Labels: category-enhancement

#185 Show fully qualified paths for external items
  cargo-public-api/tests/expected-output/diff_published.txt
  cargo-public-api/tests/expected-output/example_api-v0.3.0.txt
  cargo-public-api/tests/expected-output/example_api_diff_v0.1.0_to_v0.2.0.txt
  cargo-public-api/tests/expected-output/example_api_diff_v0.1.0_to_v0.2.0_colored.txt
  cargo-public-api/tests/expected-output/example_api_v0.3.0_colored.txt
  cargo-public-api/tests/expected-output/features-featall.txt
  cargo-public-api/tests/expected-output/features-featnone.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_afeature_bfeature_c.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_b.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_c.txt
  cargo-public-api/tests/expected-output/lint_error_list.txt
  cargo-public-api/tests/expected-output/public_api_list.txt
  cargo-public-api/tests/expected-output/rustdoc_json_list.txt
  cargo-public-api/tests/expected-output/test_repo_api_latest.txt
  public-api/public-api.txt
  public-api/src/render.rs
  public-api/tests/expected-output/comprehensive_api.txt
  public-api/tests/expected-output/diff_with_added_items.txt
  public-api/tests/expected-output/diff_with_removed_items.txt
  public-api/tests/expected-output/example_api-v0.2.0-with-blanket-implementations.txt
  public-api/tests/expected-output/print_diff.txt
  public-api/tests/expected-output/print_diff_reversed.txt
  rustdoc-json/public-api.txt
Labels: category-enhancement

#205 Enable clap help message text wrapping
  Cargo.lock
  cargo-public-api/Cargo.toml
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-exclude

#200 rustdoc-json: Remove deprecated `BuildOptions` and `fn build(...)`
  cargo-public-api/tests/expected-output/rustdoc_json_list.txt
  rustdoc-json/CHANGELOG.md
  rustdoc-json/public-api.txt
  rustdoc-json/src/lib.rs
Labels: category-exclude

#201 Include Blanket and Auto Trait `impl`s by default; use `--simplified` to opt-out
  README.md
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/diff_published.txt
  cargo-public-api/tests/expected-output/example_api-v0.3.0.txt
  cargo-public-api/tests/expected-output/example_api_diff_v0.1.0_to_v0.2.0.txt
  cargo-public-api/tests/expected-output/example_api_diff_v0.1.0_to_v0.2.0_colored.txt
  cargo-public-api/tests/expected-output/example_api_v0.3.0_colored.txt
  cargo-public-api/tests/expected-output/features-featall.txt
  cargo-public-api/tests/expected-output/features-featnone.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_afeature_bfeature_c.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_b.txt
  cargo-public-api/tests/expected-output/features-featnonefeature_c.txt
  cargo-public-api/tests/expected-output/lint_error_list.txt
  cargo-public-api/tests/expected-output/public_api_list.txt
  cargo-public-api/tests/expected-output/rustdoc_json_list.txt
  cargo-public-api/tests/expected-output/test_repo_api_latest.txt
  docs/CI-EXAMPLES.md
  public-api/public-api.txt
  public-api/src/item_processor.rs
  public-api/src/lib.rs
  public-api/src/main.rs
  public-api/tests/expected-output/comprehensive_api.txt
  public-api/tests/expected-output/diff_with_added_items.txt
  public-api/tests/expected-output/diff_with_removed_items.txt
  public-api/tests/expected-output/example_api-v0.2.0-not-simplified
  public-api/tests/expected-output/example_api-v0.2.0-not-simplified.txt
  public-api/tests/expected-output/print_diff.txt
  public-api/tests/expected-output/print_diff_reversed.txt
  public-api/tests/public-api-bin-tests.rs
  public-api/tests/public-api-lib-tests.rs
  rustdoc-json/public-api.txt
  scripts/test-invocation-variants.sh
Labels: category-enhancement

#207 Print -h and --help as part of CI
  .github/workflows/CI.yml
Labels: category-exclude

#208 Replace our own `manifest_parser` with `cargo-manifest`
  Cargo.lock
  cargo-public-api/tests/expected-output/rustdoc_json_list.txt
  rustdoc-json/CHANGELOG.md
  rustdoc-json/Cargo.toml
  rustdoc-json/public-api.txt
  rustdoc-json/src/build.rs
  rustdoc-json/src/lib.rs
  rustdoc-json/src/manifest_parser.rs
Labels: category-exclude

#209 Allow omitting package name when diffing against crates.io
  Cargo.lock
  cargo-public-api/Cargo.toml
  cargo-public-api/src/published_crate.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-enhancement

#211 Run feature tests in parallel
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-exclude

#213 Build more tests with independent target dirs
  cargo-public-api/src/main.rs
  cargo-public-api/src/published_crate.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  docs/CONTRIBUTING.md
  rustdoc-json/CHANGELOG.md
  rustdoc-json/public-api.txt
  rustdoc-json/src/build.rs
Labels: category-exclude

#216 Move some tests from `test-invocation-variants.sh` to `cargo test`
  .github/workflows/CI.yml
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/test_repo_api_latest_not_simplified.txt
  scripts/test-invocation-variants.sh
  test-utils/src/lib.rs
Labels: category-exclude

#227 Auto-bless via EnselicCICD fork to trigger CI on PR
  .github/workflows/Nightly.yml
  scripts/auto-bless.sh
  scripts/test-invocation-variants.sh
Labels: category-exclude

#230 Bless `nightly-2022-11-29` output
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/public-api.txt
  public-api/tests/expected-output/comprehensive_api.txt
  test-utils/MINIMUM_RUSTDOC_JSON_VERSION_FOR_TESTS
Labels: category-exclude
