Repository cargo-public-api/cargo-public-api, pull requests merged in 2022-12, with the labels that each got.

#215 Replace `test-invocation-variants.sh` with `cargo test`
  .github/workflows/CI.yml
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  docs/CONTRIBUTING.md
  scripts/run-ci-locally.sh
  scripts/test-invocation-variants.sh
  test-utils/src/lib.rs
Labels: category-exclude

#231 Introduce new `rustup-toolchain` crate
  Cargo.lock
  Cargo.toml
  cargo-public-api/Cargo.toml
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  rustup-toolchain/Cargo.toml
  rustup-toolchain/README.md
  rustup-toolchain/src/lib.rs
  test-utils/src/lib.rs
Labels: category-exclude

#232 Use `expect-test` crate instead of our own solution
  Cargo.lock
  cargo-public-api/Cargo.toml
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  public-api/Cargo.toml
  public-api/tests/expected-output/diff_with_added_items.txt
  public-api/tests/expected-output/diff_with_removed_items.txt
  public-api/tests/expected-output/no_diff.txt
  public-api/tests/public-api-bin-tests.rs
  public-api/tests/public-api-lib-tests.rs
  scripts/bless-expected-output-for-tests.sh
  test-utils/Cargo.toml
  test-utils/src/assert_or_bless.rs
  test-utils/src/lib.rs
Labels: category-exclude

#234 Introduce `trait ApiSource` for a more powerful architecture
  cargo-public-api/src/api_source.rs
  cargo-public-api/src/main.rs
  cargo-public-api/src/published_crate.rs
Labels: category-exclude

#235 Add new CLI for diffing: a `diff` subcommand
  Cargo.lock
  cargo-public-api/Cargo.toml
  cargo-public-api/src/api_source.rs
  cargo-public-api/src/git_utils.rs
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-enhancement

#239 Interpret `--color` as `--color=always`
  cargo-public-api/src/main.rs
  cargo-public-api/src/plain.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  docs/long-help.txt
  docs/short-help.txt
Labels: category-enhancement

#240 Hide `--toolchain` from `-h`/`--help`
  cargo-public-api/src/main.rs
  docs/long-help.txt
  docs/short-help.txt
Labels: category-exclude

#252 Group impl blocks together with their respective functions
  public-api/src/intermediate_public_item.rs
  public-api/src/public_item.rs
  public-api/src/render.rs
  public-api/tests/expected-output/comprehensive_api.txt
  test-apis/comprehensive_api/src/impls.rs
Labels: category-enhancement

#255 Add check for `$CARGO_HOME/bin/cargo-public-api` to avoid problems with tests
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-exclude

#257 Make it easy to preserve test repos to debug test failures
  Cargo.lock
  cargo-public-api/Cargo.toml
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-exclude

#258 Remove deprecated `--diff` CLI
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-other

#259 Remove `diff crate-name@0.1.0` support, use `-p crate-name diff 0.1.0` instead
  cargo-public-api/src/published_crate.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-other

#261 Put auto derived `impl`s (`Clone`, `Debug`, etc) right after normal `impl`s
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/public-api.txt
  public-api/src/item_processor.rs
  rustdoc-json/public-api.txt
  rustup-toolchain/public-api.txt
Labels: category-other

#262 If `--simplifed` is passed twice, omit auto derived `impl`s (`Clone`, `Debug`, etc)
  cargo-public-api/src/api_source.rs
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/omit-auto-derived-impls.txt
  cargo-public-api/tests/expected-output/public_api_list.txt
  docs/long-help.txt
  docs/short-help.txt
  public-api/public-api.txt
  public-api/src/item_processor.rs
  public-api/src/lib.rs
Labels: category-enhancement

#263 Remove deprecated `public_api::Options::with_blanket_implementations`
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/CHANGELOG.md
  public-api/public-api.txt
  public-api/src/lib.rs
Labels: category-exclude
