Repository cargo-public-api/cargo-public-api, pull requests merged in 2022-10, with the labels that each got.

#169 Make auto-generated release notes higher-resolution
  .github/release.yml
  .github/workflows/Peek-release-notes.yml
  docs/MAINTAINER.md
Labels: category-exclude

#171 Allow to specify `--target-dir` when building rustdoc JSON
  cargo-public-api/tests/expected-output/rustdoc_json_list.txt
  public-api/tests/public-api-bin-tests.rs
  rustdoc-json/CHANGELOG.md
  rustdoc-json/public-api.txt
  rustdoc-json/src/build.rs
  rustdoc-json/src/lib.rs
  test-utils/src/lib.rs
Labels: category-public_api

#174 Add option `--force-git-checkouts` to force git checkouts
  cargo-public-api/src/git_utils.rs
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-enhancement

#177 Support `std` and `core` pre-built JSON via new `--rustdoc-json` option
  Cargo.lock
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  public-api/Cargo.toml
  public-api/src/render.rs
Labels: category-enhancement

#178 Render supertraits of traits
  public-api/src/render.rs
  public-api/tests/expected-output/comprehensive_api.txt
  test-apis/comprehensive_api/src/traits.rs
Labels: category-bugfix

#184 cargo-public-api: Introduce `toolchain` mod
  cargo-public-api/src/main.rs
  cargo-public-api/src/toolchain.rs
Labels: category-exclude

#186 Fix `version.workspace = true` crash by bumping `cargo_toml` to `0.13.0`
  Cargo.lock
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/workspace-version.txt
  cargo-public-api/tests/virtual-manifest/Cargo.toml
  cargo-public-api/tests/virtual-manifest/workspace-version/Cargo.toml
  cargo-public-api/tests/virtual-manifest/workspace-version/src/lib.rs
  rustdoc-json/Cargo.toml
Labels: category-bugfix

#187 Add smart `--diff` shorthand for `--diff-git-checkouts` and `--diff-rustdoc-json`
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-enhancement

#188 `public_api`: Introduce private `mod public_item`
  public-api/src/diff.rs
  public-api/src/item_iterator.rs
  public-api/src/lib.rs
  public-api/src/public_item.rs
  public-api/src/render.rs
  public-api/src/tokens.rs
Labels: category-exclude

#189 Rename `PublicItemsDiff` to `PublicApiDiff`
  cargo-public-api/src/main.rs
  cargo-public-api/src/plain.rs
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/examples/diff_public_api.rs
  public-api/public-api.txt
  public-api/src/diff.rs
  public-api/src/lib.rs
  public-api/src/main.rs
  public-api/src/public_item.rs
  public-api/tests/expected-output/diff_with_added_items.txt
  public-api/tests/expected-output/diff_with_removed_items.txt
  public-api/tests/expected-output/no_diff.txt
  public-api/tests/public-api-lib-tests.rs
Labels: category-public_api

#190 Make `PublicApiDiff::between(...)` take `PublicApi`s instead of `Vec<PublicItem>`s
  cargo-public-api/src/main.rs
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/examples/diff_public_api.rs
  public-api/public-api.txt
  public-api/src/diff.rs
  public-api/src/main.rs
  public-api/tests/public-api-lib-tests.rs
Labels: category-public_api

#191 Hide `PublicApi::items` behind `PublicApi::items()` iterator
  cargo-public-api/src/main.rs
  cargo-public-api/src/plain.rs
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/examples/list_public_api.rs
  public-api/public-api.txt
  public-api/src/diff.rs
  public-api/src/lib.rs
  public-api/src/main.rs
  public-api/tests/public-api-lib-tests.rs
Labels: category-public_api

#182 Validate and resolve CLI commit references
  cargo-public-api/src/git_utils.rs
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-enhancement

#194 Start using workspace.package.version
  Cargo.toml
  cargo-public-api/Cargo.toml
  docs/MAINTAINER.md
  public-api/Cargo.toml
Labels: category-exclude

#195 Begin rendering all `impl`s by rewriting how items are processed
  cargo-public-api/src/main.rs
  cargo-public-api/tests/expected-output/example_api-v0.3.0.txt
  cargo-public-api/tests/expected-output/example_api_v0.3.0_colored.txt
  cargo-public-api/tests/expected-output/public_api_list.txt
  cargo-public-api/tests/expected-output/rustdoc_json_list.txt
  cargo-public-api/tests/expected-output/test_repo_api_latest.txt
  public-api/public-api.txt
  public-api/src/intermediate_public_item.rs
  public-api/src/item_iterator.rs
  public-api/src/item_processor.rs
  public-api/src/lib.rs
  public-api/src/public_item.rs
  public-api/src/render.rs
  public-api/tests/expected-output/comprehensive_api.txt
  public-api/tests/expected-output/example_api-v0.2.0-with-blanket-implementations.txt
  rustdoc-json/public-api.txt
  test-apis/comprehensive_api/src/impls.rs
Labels: category-enhancement
