Repository cargo-public-api/cargo-public-api, pull requests merged in 2023-01, with the labels that each got.

#264 Split `public_api::Options::simplified` into `::omit_auto_trait_impls` and `::omit_blanket_impls`
  cargo-public-api/src/api_source.rs
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/CHANGELOG.md
  public-api/public-api.txt
  public-api/src/item_processor.rs
  public-api/src/lib.rs
  public-api/src/main.rs
  public-api/tests/expected-output/example_api-v0.2.0-omit_auto_trait_impls.txt
  public-api/tests/expected-output/example_api-v0.2.0-omit_blanket_impls.txt
  public-api/tests/expected-output/example_api-v0.2.0-simplified_without_auto_derived_impls.txt
  public-api/tests/public-api-lib-tests.rs
Labels: category-exclude

#260 Support `cargo public-api diff latest`
  .github/workflows/CI.yml
  Cargo.lock
  cargo-public-api/Cargo.toml
  cargo-public-api/src/main.rs
  cargo-public-api/src/published_crate.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/diff-latest.txt
  docs/long-diff-help.txt
  scripts/run-ci-locally.sh
Labels: category-enhancement

#265 Fix rendering of bounds for Generic Associated Types (GATs)
  public-api/src/render.rs
  public-api/tests/expected-output/comprehensive_api.txt
  test-apis/comprehensive_api/src/traits.rs
Labels: category-bugfix

#266 Bump minimum nightly version to `nightly-2023-01-04`
  Cargo.lock
  Cargo.toml
  README.md
  cargo-public-api/Cargo.toml
  cargo-public-api/MINIMUM_RUSTDOC_JSON_VERSION_FOR_TESTS
  public-api/CHANGELOG.md
  public-api/Cargo.toml
  public-api/README.md
  public-api/src/item_processor.rs
  public-api/src/lib.rs
  public-api/src/render.rs
  repo-tests/Cargo.toml
  rustdoc-json/Cargo.toml
  rustup-toolchain/Cargo.toml
Labels: category-other

#267 CI: Start running `cargo audit`
  .github/workflows/CI.yml
  scripts/cargo-audit.sh
  scripts/run-ci-locally.sh
Labels: category-exclude

#268 Replace `sub_prefix` with `ImplKind::Inherent`
  public-api/src/intermediate_public_item.rs
  public-api/src/item_processor.rs
Labels: category-exclude

#269 Group `impl`s better, make sorting more lexicographic
  cargo-public-api/tests/expected-output/public_api_list.txt
  cargo-public-api/tests/expected-output/test_repo_api_latest_not_simplified.txt
  public-api/public-api.txt
  public-api/src/intermediate_public_item.rs
  public-api/tests/expected-output/comprehensive_api.txt
  public-api/tests/expected-output/diff_with_added_items.txt
  public-api/tests/expected-output/diff_with_removed_items.txt
  public-api/tests/expected-output/example_api-v0.2.0-not-simplified.txt
  public-api/tests/expected-output/example_api-v0.2.0-omit_auto_trait_impls.txt
  public-api/tests/expected-output/example_api-v0.2.0-omit_blanket_impls.txt
  rustdoc-json/public-api.txt
  rustup-toolchain/public-api.txt
Labels: category-bugfix

#272 Enable DependaBot for dependency updates
  .github/dependabot.yml
Labels: category-exclude

#275 migrate to node16 actions
  .github/workflows/CI.yml
  .github/workflows/Nightly.yml
  .github/workflows/Release-cargo-public-api.yml
  .github/workflows/Release-rustdoc-json.yml
  .github/workflows/Release-rustup-toolchain.yml
  docs/CI-EXAMPLES.md
Labels: category-exclude

#270 Properly group multiple inherent `impl`s
  cargo-public-api/tests/expected-output/public_api_list.txt
  public-api/CHANGELOG.md
  public-api/public-api.txt
  public-api/src/diff.rs
  public-api/src/intermediate_public_item.rs
  public-api/src/lib.rs
  public-api/src/public_item.rs
  public-api/tests/common/mod.rs
  public-api/tests/expected-output/comprehensive_api.txt
  public-api/tests/expected-output/diff_move_item_between_inherent_impls.txt
  public-api/tests/public-api-lib-tests.rs
Labels: category-bugfix

#276 CI: Use plain `rustup install` instead of `dtolnay/rust-toolchain`
  .github/workflows/CI.yml
  .github/workflows/Nightly.yml
  docs/CI-EXAMPLES.md
Labels: category-exclude

#271 CI: Start running `cargo deny check`, mostly to checks licences of deps
  .github/workflows/CI.yml
  deny.toml
  repo-tests/Cargo.toml
  scripts/cargo-deny.sh
  scripts/run-ci-locally.sh
Labels: category-exclude

#277 CI: Stop giving `softprops/action-gh-release` access to crates.io token
  .github/workflows/Release-cargo-public-api.yml
Labels: category-exclude

#278 README.md: Improve Installation instructions
  README.md
  repo-tests/tests/repo-tests.rs
Labels: category-exclude

#284 satisfy clippy
  cargo-public-api/src/api_source.rs
  cargo-public-api/src/main.rs
  cargo-public-api/src/plain.rs
  cargo-public-api/src/published_crate.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  public-api/examples/diff_public_api.rs
  public-api/examples/list_public_api.rs
  public-api/src/lib.rs
  public-api/src/main.rs
  public-api/tests/public-api-bin-tests.rs
  public-api/tests/public-api-lib-tests.rs
  repo-tests/tests/repo-tests.rs
  rustdoc-json/examples/build-rustdoc-json.rs
Labels: category-exclude

#281 CI-EXAMPLES.md: Only recommend the `cargo test` approach
  docs/CI-EXAMPLES.md
Labels: category-exclude

#280 README.md: Rewrite 'how to diff' section
  README.md
  docs/img/diff-specific-published-version.webp
  docs/img/diff.jpg
  docs/img/list-truncated.webp
  docs/img/list.jpg
  repo-tests/tests/repo-tests.rs
Labels: category-exclude

#286 MAINTAINER.md: Add version rule: bump 0.x.0 when item appearance changes
  docs/CI-EXAMPLES.md
  docs/MAINTAINER.md
Labels: category-exclude

#291 Rename `MINIMUM_RUSTDOC_JSON_VERSION` to `MINIMUM_NIGHTLY_VERSION` for clarity
  .github/workflows/Nightly.yml
  README.md
  cargo-public-api/src/api_source.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/public_api_list.txt
  docs/RELEASE.md
  public-api/CHANGELOG.md
  public-api/public-api.txt
  public-api/src/lib.rs
  public-api/src/main.rs
  public-api/tests/public-api-bin-tests.rs
  repo-tests/tests/repo-tests.rs
Labels: category-exclude

#292 Change `rustdoc_json::Builder::toolchain(...)` to take `Into<String>`
  README.md
  cargo-public-api/src/api_source.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  public-api/examples/diff_public_api.rs
  public-api/examples/list_public_api.rs
  public-api/tests/common/mod.rs
  public-api/tests/public-api-lib-tests.rs
  rustdoc-json/CHANGELOG.md
  rustdoc-json/README.md
  rustdoc-json/examples/build-rustdoc-json.rs
  rustdoc-json/public-api.txt
  rustdoc-json/src/builder.rs
  rustdoc-json/src/lib.rs
  rustdoc-json/tests/rustdoc-json-lib-tests.rs
  rustup-toolchain/tests/rustup-toolchain-lib-tests.rs
Labels: category-exclude

#296 Make `diff latest` diff highest semver version, not most recently published
  README.md
  cargo-public-api/src/main.rs
  cargo-public-api/src/published_crate.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/diff-highest.txt
  cargo-public-api/tests/expected-output/diff-latest.txt
  docs/long-diff-help.txt
Labels: category-enhancement

#295 Deprecate `PublicApi::from_rustdoc_json_str()`
  cargo-public-api/src/api_source.rs
  public-api/CHANGELOG.md
  public-api/src/diff.rs
  public-api/src/lib.rs
  public-api/tests/public-api-lib-tests.rs
Labels: category-public-api

#279 When diffing, build rustdoc JSON with `--cap-lints allow` by default
  cargo-public-api/src/api_source.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/create_test_git_repo/mod.rs
  test-apis/lint_error/Cargo.toml
Labels: category-other

#289 correctly add features when using cache
  Cargo.lock
  Cargo.toml
  cargo-public-api/Cargo.toml
  cargo-public-api/src/published_crate.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/expected-output/diff_published_with_features.txt
  test-apis/example_api-v0.2.1/Cargo.toml
  test-apis/example_api-v0.2.1/src/lib.rs
Labels: category-bugfix

#303 Bump `crates-index` to `0.19.0`; `0.18.12` is yanked
  Cargo.lock
  cargo-public-api/Cargo.toml
  deny.toml
Labels: category-exclude

#304 deny.toml: Deny multiple-versions except for toml
  deny.toml
Labels: category-exclude

#305 Make get_host_target_triple() more portable, do not depend on sed
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
Labels: category-exclude

#307 Start using let-else to pass pedantic Clippy 1.67
  cargo-public-api/src/main.rs
  cargo-public-api/src/toolchain.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  public-api/src/render.rs
  repo-tests/tests/repo-tests.rs
Labels: category-exclude

#306 Run more tests on Windows
  cargo-public-api/src/main.rs
  cargo-public-api/tests/cargo-public-api-bin-tests.rs
  cargo-public-api/tests/create_test_git_repo/mod.rs
  docs/long-diff-help.txt
  docs/long-help.txt
  docs/short-diff-help.txt
  docs/short-help.txt
  public-api/tests/public-api-bin-tests.rs
Labels: category-exclude

#308 Bump `crates-index` to `0.19.1` to get rid of MPL:ed `smartstring`
  Cargo.lock
  cargo-public-api/Cargo.toml
  deny.toml
Labels: category-exclude
